services:
  # Backend (Flask)
  - type: web
    name: sinfini-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_DEBUG
        value: "0"

  # Frontend (React)
  - type: web
    name: sinfini-frontend
    env: node
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s build -l $PORT  # serve production build
